### ISSUE TITLE
chunks too big issue

### ISSUE THREAD

**Issue by PhanaticD** [Creeperface01/Nukkit#36]
I am using nukkit-gt1.2 build 53 from here: https://ci.potestas.xyz/job/Nukkit-GT1.2/changes

```
2017-10-14 03:14:57 [ERROR] Error while unloading a chunk: java.lang.RuntimeException: cn.nukkit.utils.ChunkException: Chunk is too big! 1726472 > 1048576^M
2017-10-14 03:14:57 [ALERT] java.lang.RuntimeException: cn.nukkit.utils.ChunkException: Chunk is too big! 1726472 > 1048576
    at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:279)
    at cn.nukkit.level.Level.unloadChunk(Level.java:2681)
    at cn.nukkit.level.Level.unloadChunk(Level.java:2641)
    at cn.nukkit.level.Level.unloadChunks(Level.java:2939)
    at cn.nukkit.level.Level.unloadChunks(Level.java:2917)
    at cn.nukkit.level.Level.doTick(Level.java:769)
    at cn.nukkit.Server.checkTickUpdates(Server.java:926)
    at cn.nukkit.Server.tick(Server.java:1001)
    at cn.nukkit.Server.tickProcessor(Server.java:799)
    at cn.nukkit.Server.start(Server.java:778)
    at cn.nukkit.Server.<init>(Server.java:469)
    at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: cn.nukkit.utils.ChunkException: Chunk is too big! 1726472 > 1048576
    at cn.nukkit.level.format.anvil.RegionLoader.saveChunk(RegionLoader.java:91)
    at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.java:144)
    at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:277)
    ... 11 more
^M
2017-10-14 03:15:38 [ERROR] Error while unloading a chunk: java.lang.RuntimeException: cn.nukkit.utils.ChunkException: Chunk is too big! 1725056 > 1048576^M
2017-10-14 03:15:38 [ALERT] java.lang.RuntimeException: cn.nukkit.utils.ChunkException: Chunk is too big! 1725056 > 1048576
    at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:279)
    at cn.nukkit.level.Level.unloadChunk(Level.java:2681)
    at cn.nukkit.level.Level.unloadChunk(Level.java:2641)
    at cn.nukkit.level.Level.unloadChunks(Level.java:2939)
    at cn.nukkit.level.Level.unloadChunks(Level.java:2917)
    at cn.nukkit.level.Level.doTick(Level.java:769)
    at cn.nukkit.Server.checkTickUpdates(Server.java:926)
    at cn.nukkit.Server.tick(Server.java:1001)
    at cn.nukkit.Server.tickProcessor(Server.java:799)
    at cn.nukkit.Server.start(Server.java:778)
    at cn.nukkit.Server.<init>(Server.java:469)
    at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: cn.nukkit.utils.ChunkException: Chunk is too big! 1725056 > 1048576
    at cn.nukkit.level.format.anvil.RegionLoader.saveChunk(RegionLoader.java:91)
    at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.java:144)
    at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:277)
    ... 11 more
^M
2017-10-14 03:16:15 [ERROR] Error while unloading a chunk: java.lang.RuntimeException: cn.nukkit.utils.ChunkException: Chunk is too big! 1724296 > 1048576^M
2017-10-14 03:16:15 [ALERT] java.lang.RuntimeException: cn.nukkit.utils.ChunkException: Chunk is too big! 1724296 > 1048576
    at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:279)
    at cn.nukkit.level.Level.unloadChunk(Level.java:2681)
    at cn.nukkit.level.Level.unloadChunk(Level.java:2641)
    at cn.nukkit.level.Level.unloadChunks(Level.java:2939)
    at cn.nukkit.level.Level.unloadChunks(Level.java:2917)
    at cn.nukkit.level.Level.doTick(Level.java:769)
    at cn.nukkit.Server.checkTickUpdates(Server.java:926)
    at cn.nukkit.Server.tick(Server.java:1001)
    at cn.nukkit.Server.tickProcessor(Server.java:799)
    at cn.nukkit.Server.start(Server.java:778)
    at cn.nukkit.Server.<init>(Server.java:469)
    at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: cn.nukkit.utils.ChunkException: Chunk is too big! 1724296 > 1048576
    at cn.nukkit.level.format.anvil.RegionLoader.saveChunk(RegionLoader.java:91)
    at cn.nukkit.level.format.anvil.RegionLoader.writeChunk(RegionLoader.java:144)
    at cn.nukkit.level.format.anvil.Anvil.saveChunk(Anvil.java:277)
    ... 11 more
```

**Comment by Creeperface01** [comment]
Your world is probably corrupted

**Comment by PhanaticD** [comment]
how so? i just set it up a few days ago

**Comment by Creeperface01** [comment]
Do you use world generated in nukkit?

**Comment by PhanaticD** [comment]
plotsquared plugin is the generator
