### ISSUE TITLE
Player join server error

### ISSUE THREAD

**Issue by WetABQ** [Creeperface01/Nukkit#42]
### Issue Description

java.lang.NoSuchMethodError: cn.nukkit.AdventureSettings.setCanFly(Z)V
        at world.protect.Listener.EventListener.setGamemode(EventListener.java:62)
        at world.protect.Listener.EventListener.setIf(EventListener.java:68)
        at world.protect.Listener.EventListener.onPlayerJoinEvent(EventListener.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 10 more

### Steps to Reproduce the Issue

1. join server

### OS and Versions

* Nukkit Version: ?? 

* Java Version: 
```
??
```

* Host Configuration: 

| Item | Value |
|:----:|:-----:|
| Host OS | ?? |  
| Memory(RAM) | ?? GB | 
| Storage Size | ?? GB | 
| Storage Type | ?? | 
| CPU Type | ?? | 
| CPU Core Count | ?? cores ?? threads | 
| Upstream Bandwidth | ?? | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | ?? | 
| Client Version | ?? | 

### Crashdump, Backtrace or Other Files
java.lang.NoSuchMethodError: cn.nukkit.AdventureSettings.setCanFly(Z)V
        at world.protect.Listener.EventListener.setGamemode(EventListener.java:62)
        at world.protect.Listener.EventListener.setIf(EventListener.java:68)
        at world.protect.Listener.EventListener.onPlayerJoinEvent(EventListener.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 10 more

**Comment by WetABQ** [comment]
And how to add an ElementButton in WindowCustom?

**Comment by Creeperface01** [comment]
Its a plugin issue
